lsi: false
safe: true
source: ./jekyll-test
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

lang: 'zh-TW'
title: '測試網站'
plugins: ["jekyll-paginate"]
paginate: 20
paginate_path: "/blog/page:num/"
